/**
* Recipe Puppy
* Recipe Puppy
*
* OpenAPI spec version: 1.0.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package me.sanchez.shared.models

import kotlinx.serialization.Serializable

import kotlinx.serialization.SerialName

/**
 * 
 * @param message 
 * @param code 
 */
@Serializable
data class ErrorModel (
    @SerialName("message")
    val message: kotlin.String,
    @SerialName("code")
    val code: kotlin.Int
) {

}

