/**
* Recipe Puppy
* Recipe Puppy
*
* OpenAPI spec version: 1.0.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package me.sanchez.shared.models

import kotlinx.serialization.Serializable

import kotlinx.serialization.SerialName

/**
 * 
 * @param title 
 * @param href 
 * @param ingredients 
 * @param thumbnail 
 */
@Serializable
data class Recipe (
    @SerialName("href")
    val href: kotlin.String,
    @SerialName("title")
    val title: kotlin.String? = null,
    @SerialName("ingredients")
    val ingredients: kotlin.String? = null,
    @SerialName("thumbnail")
    val thumbnail: kotlin.String? = null
) {

}

